### ISSUE TITLE
tidyterra

### ISSUE THREAD

**Issue by stineb** [padasch/tutorial_digital_soil_mapping#1]
Error when doing `quarto render`:

```r
Quitting from lines 95-107 [unnamed-chunk-5] (02-data_preparation.qmd)
Error in `loadNamespace()`:
! es gibt kein Paket namens 'tidyterra'
Backtrace:
 1. base::loadNamespace(x)
 2. base::withRestarts(stop(cond), retry_loadNamespace = function() NULL)
 3. base (local) withOneRestart(expr, restarts[[1L]])
 4. base (local) doWithOneRestart(return(expr), restart)
Ausführung angehalten
```

I have installed the package and made a `renv::snapshot()`. Still getting this error.

**Comment by padasch** [comment]
I tested my code with Pepa, and it worked on her machine without this error. And since it works on my mac too, I guess the problem lies with your setup, but I cannot tell where and why. Can you open the project and run these lines in the R console and see if it works?

```r
renv::status()
renv::load()
renv::restore()
install.packages("quarto")
quarto::quarto_render("book")
```

khufkens/handful_of_pixels#28

**Comment by khufkens** [comment]
@padasch Thanks. You can switch the local renderer in the github workflow to macos-latest to see if this is consistent on a "fresh" macos machine.

**Comment by padasch** [comment]
@khufkens Since I am not rendering through GitHub actions - just publishing it -, changing to macos-latest would not change anything. Or do I not understand your comment correctly?

**Comment by khufkens** [comment]
You would see if at least the libraries are correctly loaded. The render step might fail though.
