### ISSUE TITLE
Coordinate transformations

### ISSUE THREAD

**Issue by khufkens** [padasch/tutorial_digital_soil_mapping#2]
Hi Pascale,

I'm adding more elaborate geoprocessing examples to my course. I noticed you used {sp} for coordinate transformations, which is rather elaborate (and the package will be deprecated - not as fast as {raster} but still). I think {sf} might be easier. I need to add this to the course still, but I've opened a short demo issue.

https://github.com/khufkens/handful_of_pixels/issues/36

Feel free to grab things there if you think this is useful.

Cheers,
K

**Comment by padasch** [comment]
Thanks for your input! I had some code lying around from another project, using {sf} and being much more straightforward. I am updating my tutorial right away.

```
change_coords <- function(data, from_CRS, to_CRS) {
  
  # Check if data input is correct
  if (!all(names(data) %in% c("id", "lat", "lon"))) {
    stop("Input data needs variables: id, lat, lon")
  }
  
  # Create simple feature for old CRS
  sf_old_crs <- sf::st_as_sf(data, coords = c("lon", "lat"), crs = from_CRS)
  
  # Transform to new CRS
  sf_new_crs     <- sf::st_transform(sf_old_crs, crs = to_CRS)
  sf_new_crs$lat <- sf::st_coordinates(sf_new_crs)[, "Y"]
  sf_new_crs$lon <- sf::st_coordinates(sf_new_crs)[, "X"]
  
  sf_new_crs <- sf_new_crs |> dplyr::as_tibble() |> dplyr::select(id, lat, lon)
  
  # Return new CRS
  return(sf_new_crs)
}
```

**Comment by khufkens** [comment]
I missed the `st_coordinates()` function, thanks!  Could probably use this in my section rather than the mapping and unlisting. 

These packages are getting so wild these day, especially the tidyverse ones that it's hard to figure out if and where there are functions for certain things.

**Comment by khufkens** [comment]
Solution without an additional function

```r
# transformation to
# swiss coordinate system
df_sf_swiss <- df_sf |>
  st_transform(crs = "epsg:2056")

# return to simple data frame
df_swiss <- df_sf_swiss |>
  dplyr::as_tibble() |>
  dplyr::mutate(
    swis_x = st_coordinates(geometry)[, "X"],
    swiss_y = st_coordinates(geometry)[, "Y"]
    ) |>
  dplyr::select(
    -geometry
  )

```
